package org.example;

import java.util.Collections;
import java.util.Map;

import com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measurement;
import com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue;

import io.confluent.kafka.serializers.AbstractKafkaSchemaSerDeConfig;
import io.confluent.kafka.streams.serdes.avro.GenericAvroSerde;
import io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde;
import lombok.Getter;
import org.apache.avro.generic.GenericRecord;
import org.apache.kafka.common.serialization.Serde;

@Getter
public class CustomSerdes {

    private final Serde<GenericRecord> genericRecordSerde;
    private final Serde<ReducedEventValue> reducedEventValueSerde;
    private final Serde<Measurement> measurementSerde;

    public CustomSerdes(String schemaRegistryUrl) {
        Map<String, String> serdeConfig =
                Collections.singletonMap(AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, schemaRegistryUrl);
        this.genericRecordSerde = new GenericAvroSerde();

        this.reducedEventValueSerde = new SpecificAvroSerde<>();
        this.measurementSerde = new SpecificAvroSerde<>();
        genericRecordSerde.configure(serdeConfig, false);
        reducedEventValueSerde.configure(serdeConfig, false);
        measurementSerde.configure(serdeConfig, false);
    }

}
