/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2;
@org.apache.avro.specific.AvroGenerated
public enum EventName implements org.apache.avro.generic.GenericEnumSymbol<EventName> {
  MEASURE_CREATED, MEASURE_UPDATED, MEASURE_DELETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventName\",\"namespace\":\"com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2\",\"symbols\":[\"MEASURE_CREATED\",\"MEASURE_UPDATED\",\"MEASURE_DELETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
