/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2;
@org.apache.avro.specific.AvroGenerated
public enum MeasureType implements org.apache.avro.generic.GenericEnumSymbol<MeasureType> {
  SNAPSHOT, WINDOW  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MeasureType\",\"namespace\":\"com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2\",\"symbols\":[\"SNAPSHOT\",\"WINDOW\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
