/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Complete value of the measure */
@org.apache.avro.specific.AvroGenerated
public class Measure extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6107135849780507776L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Measure\",\"namespace\":\"com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2\",\"doc\":\"Complete value of the measure\",\"fields\":[{\"name\":\"partition\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED'\",\"default\":null},{\"name\":\"value\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"},{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}],\"doc\":\"Default measure value: I.e. 142\",\"default\":null},{\"name\":\"timeFrame\",\"type\":[{\"type\":\"record\",\"name\":\"WindowTime\",\"doc\":\"Definition for windowed timeFrames\",\"fields\":[{\"name\":\"from\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'\",\"default\":null},{\"name\":\"to\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'\",\"default\":null}]},{\"type\":\"record\",\"name\":\"InstantTime\",\"doc\":\"Definition for instant timeFrames\",\"fields\":[{\"name\":\"timestamp\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Instant timestamp for the measurement. I.e. '2021-03-24 10:50:00.000Z'\",\"default\":null}]}],\"doc\":\"TimeFrame for the measurement, it can ve an instant time or window time\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Measure> ENCODER =
      new BinaryMessageEncoder<Measure>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Measure> DECODER =
      new BinaryMessageDecoder<Measure>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Measure> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Measure> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Measure> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Measure>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Measure to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Measure from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Measure instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Measure fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED' */
   private java.lang.String partition;
  /** Default measure value: I.e. 142 */
   private java.lang.Object value;
  /** TimeFrame for the measurement, it can ve an instant time or window time */
   private java.lang.Object timeFrame;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Measure() {}

  /**
   * All-args constructor.
   * @param partition Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED'
   * @param value Default measure value: I.e. 142
   * @param timeFrame TimeFrame for the measurement, it can ve an instant time or window time
   */
  public Measure(java.lang.String partition, java.lang.Object value, java.lang.Object timeFrame) {
    this.partition = partition;
    this.value = value;
    this.timeFrame = timeFrame;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return partition;
    case 1: return value;
    case 2: return timeFrame;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: partition = value$ != null ? value$.toString() : null; break;
    case 1: value = value$; break;
    case 2: timeFrame = value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'partition' field.
   * @return Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED'
   */
  public java.lang.String getPartition() {
    return partition;
  }


  /**
   * Sets the value of the 'partition' field.
   * Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED'
   * @param value the value to set.
   */
  public void setPartition(java.lang.String value) {
    this.partition = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return Default measure value: I.e. 142
   */
  public java.lang.Object getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * Default measure value: I.e. 142
   * @param value the value to set.
   */
  public void setValue(java.lang.Object value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'timeFrame' field.
   * @return TimeFrame for the measurement, it can ve an instant time or window time
   */
  public java.lang.Object getTimeFrame() {
    return timeFrame;
  }


  /**
   * Sets the value of the 'timeFrame' field.
   * TimeFrame for the measurement, it can ve an instant time or window time
   * @param value the value to set.
   */
  public void setTimeFrame(java.lang.Object value) {
    this.timeFrame = value;
  }

  /**
   * Creates a new Measure RecordBuilder.
   * @return A new Measure RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder newBuilder() {
    return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder();
  }

  /**
   * Creates a new Measure RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Measure RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder newBuilder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder other) {
    if (other == null) {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder();
    } else {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder(other);
    }
  }

  /**
   * Creates a new Measure RecordBuilder by copying an existing Measure instance.
   * @param other The existing instance to copy.
   * @return A new Measure RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder newBuilder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure other) {
    if (other == null) {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder();
    } else {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder(other);
    }
  }

  /**
   * RecordBuilder for Measure instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Measure>
    implements org.apache.avro.data.RecordBuilder<Measure> {

    /** Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED' */
    private java.lang.String partition;
    /** Default measure value: I.e. 142 */
    private java.lang.Object value;
    /** TimeFrame for the measurement, it can ve an instant time or window time */
    private java.lang.Object timeFrame;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.partition)) {
        this.partition = data().deepCopy(fields()[0].schema(), other.partition);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.timeFrame)) {
        this.timeFrame = data().deepCopy(fields()[2].schema(), other.timeFrame);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Measure instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.partition)) {
        this.partition = data().deepCopy(fields()[0].schema(), other.partition);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timeFrame)) {
        this.timeFrame = data().deepCopy(fields()[2].schema(), other.timeFrame);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'partition' field.
      * Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED'
      * @return The value.
      */
    public java.lang.String getPartition() {
      return partition;
    }


    /**
      * Sets the value of the 'partition' field.
      * Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED'
      * @param value The value of 'partition'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder setPartition(java.lang.String value) {
      validate(fields()[0], value);
      this.partition = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'partition' field has been set.
      * Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED'
      * @return True if the 'partition' field has been set, false otherwise.
      */
    public boolean hasPartition() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'partition' field.
      * Value of the parameter by which it is grouped. I.e. 'MOCACOTA_CREATED'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder clearPartition() {
      partition = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * Default measure value: I.e. 142
      * @return The value.
      */
    public java.lang.Object getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * Default measure value: I.e. 142
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder setValue(java.lang.Object value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * Default measure value: I.e. 142
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * Default measure value: I.e. 142
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeFrame' field.
      * TimeFrame for the measurement, it can ve an instant time or window time
      * @return The value.
      */
    public java.lang.Object getTimeFrame() {
      return timeFrame;
    }


    /**
      * Sets the value of the 'timeFrame' field.
      * TimeFrame for the measurement, it can ve an instant time or window time
      * @param value The value of 'timeFrame'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder setTimeFrame(java.lang.Object value) {
      validate(fields()[2], value);
      this.timeFrame = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'timeFrame' field has been set.
      * TimeFrame for the measurement, it can ve an instant time or window time
      * @return True if the 'timeFrame' field has been set, false otherwise.
      */
    public boolean hasTimeFrame() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'timeFrame' field.
      * TimeFrame for the measurement, it can ve an instant time or window time
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Measure.Builder clearTimeFrame() {
      timeFrame = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Measure build() {
      try {
        Measure record = new Measure();
        record.partition = fieldSetFlags()[0] ? this.partition : (java.lang.String) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value :  defaultValue(fields()[1]);
        record.timeFrame = fieldSetFlags()[2] ? this.timeFrame :  defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Measure>
    WRITER$ = (org.apache.avro.io.DatumWriter<Measure>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Measure>
    READER$ = (org.apache.avro.io.DatumReader<Measure>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










