/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This are the fields that identify the measure source */
@org.apache.avro.specific.AvroGenerated
public class Source extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8727233737839276484L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Source\",\"namespace\":\"com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2\",\"doc\":\"This are the fields that identify the measure source\",\"fields\":[{\"name\":\"probeName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Probe ID responsible of the measure. I.e. 'KFK'\",\"default\":null},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Data System to which the measure belongs. I.e. 'PIPE'\",\"default\":null},{\"name\":\"schema\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Schema to which the measure belongs. I.e. 'COMERCIAL'\",\"default\":null},{\"name\":\"object\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Source> ENCODER =
      new BinaryMessageEncoder<Source>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Source> DECODER =
      new BinaryMessageDecoder<Source>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Source> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Source> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Source> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Source>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Source to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Source from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Source instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Source fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Probe ID responsible of the measure. I.e. 'KFK' */
   private java.lang.String probeName;
  /** Data System to which the measure belongs. I.e. 'PIPE' */
   private java.lang.String name;
  /** Schema to which the measure belongs. I.e. 'COMERCIAL' */
   private java.lang.String schema;
  /** physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1' */
   private java.lang.String object;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Source() {}

  /**
   * All-args constructor.
   * @param probeName Probe ID responsible of the measure. I.e. 'KFK'
   * @param name Data System to which the measure belongs. I.e. 'PIPE'
   * @param schema Schema to which the measure belongs. I.e. 'COMERCIAL'
   * @param object physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
   */
  public Source(java.lang.String probeName, java.lang.String name, java.lang.String schema, java.lang.String object) {
    this.probeName = probeName;
    this.name = name;
    this.schema = schema;
    this.object = object;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return probeName;
    case 1: return name;
    case 2: return schema;
    case 3: return object;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: probeName = value$ != null ? value$.toString() : null; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: schema = value$ != null ? value$.toString() : null; break;
    case 3: object = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'probeName' field.
   * @return Probe ID responsible of the measure. I.e. 'KFK'
   */
  public java.lang.String getProbeName() {
    return probeName;
  }


  /**
   * Sets the value of the 'probeName' field.
   * Probe ID responsible of the measure. I.e. 'KFK'
   * @param value the value to set.
   */
  public void setProbeName(java.lang.String value) {
    this.probeName = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Data System to which the measure belongs. I.e. 'PIPE'
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Data System to which the measure belongs. I.e. 'PIPE'
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'schema' field.
   * @return Schema to which the measure belongs. I.e. 'COMERCIAL'
   */
  public java.lang.String getSchema$() {
    return schema;
  }


  /**
   * Sets the value of the 'schema' field.
   * Schema to which the measure belongs. I.e. 'COMERCIAL'
   * @param value the value to set.
   */
  public void setSchema$(java.lang.String value) {
    this.schema = value;
  }

  /**
   * Gets the value of the 'object' field.
   * @return physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
   */
  public java.lang.String getObject() {
    return object;
  }


  /**
   * Sets the value of the 'object' field.
   * physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
   * @param value the value to set.
   */
  public void setObject(java.lang.String value) {
    this.object = value;
  }

  /**
   * Creates a new Source RecordBuilder.
   * @return A new Source RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder newBuilder() {
    return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder();
  }

  /**
   * Creates a new Source RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Source RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder newBuilder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder other) {
    if (other == null) {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder();
    } else {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder(other);
    }
  }

  /**
   * Creates a new Source RecordBuilder by copying an existing Source instance.
   * @param other The existing instance to copy.
   * @return A new Source RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder newBuilder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source other) {
    if (other == null) {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder();
    } else {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder(other);
    }
  }

  /**
   * RecordBuilder for Source instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Source>
    implements org.apache.avro.data.RecordBuilder<Source> {

    /** Probe ID responsible of the measure. I.e. 'KFK' */
    private java.lang.String probeName;
    /** Data System to which the measure belongs. I.e. 'PIPE' */
    private java.lang.String name;
    /** Schema to which the measure belongs. I.e. 'COMERCIAL' */
    private java.lang.String schema;
    /** physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1' */
    private java.lang.String object;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.probeName)) {
        this.probeName = data().deepCopy(fields()[0].schema(), other.probeName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.schema)) {
        this.schema = data().deepCopy(fields()[2].schema(), other.schema);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.object)) {
        this.object = data().deepCopy(fields()[3].schema(), other.object);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Source instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.probeName)) {
        this.probeName = data().deepCopy(fields()[0].schema(), other.probeName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.schema)) {
        this.schema = data().deepCopy(fields()[2].schema(), other.schema);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.object)) {
        this.object = data().deepCopy(fields()[3].schema(), other.object);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'probeName' field.
      * Probe ID responsible of the measure. I.e. 'KFK'
      * @return The value.
      */
    public java.lang.String getProbeName() {
      return probeName;
    }


    /**
      * Sets the value of the 'probeName' field.
      * Probe ID responsible of the measure. I.e. 'KFK'
      * @param value The value of 'probeName'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder setProbeName(java.lang.String value) {
      validate(fields()[0], value);
      this.probeName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'probeName' field has been set.
      * Probe ID responsible of the measure. I.e. 'KFK'
      * @return True if the 'probeName' field has been set, false otherwise.
      */
    public boolean hasProbeName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'probeName' field.
      * Probe ID responsible of the measure. I.e. 'KFK'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder clearProbeName() {
      probeName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Data System to which the measure belongs. I.e. 'PIPE'
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Data System to which the measure belongs. I.e. 'PIPE'
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Data System to which the measure belongs. I.e. 'PIPE'
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * Data System to which the measure belongs. I.e. 'PIPE'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'schema' field.
      * Schema to which the measure belongs. I.e. 'COMERCIAL'
      * @return The value.
      */
    public java.lang.String getSchema$() {
      return schema;
    }


    /**
      * Sets the value of the 'schema' field.
      * Schema to which the measure belongs. I.e. 'COMERCIAL'
      * @param value The value of 'schema'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder setSchema$(java.lang.String value) {
      validate(fields()[2], value);
      this.schema = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'schema' field has been set.
      * Schema to which the measure belongs. I.e. 'COMERCIAL'
      * @return True if the 'schema' field has been set, false otherwise.
      */
    public boolean hasSchema$() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'schema' field.
      * Schema to which the measure belongs. I.e. 'COMERCIAL'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder clearSchema$() {
      schema = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'object' field.
      * physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
      * @return The value.
      */
    public java.lang.String getObject() {
      return object;
    }


    /**
      * Sets the value of the 'object' field.
      * physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
      * @param value The value of 'object'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder setObject(java.lang.String value) {
      validate(fields()[3], value);
      this.object = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'object' field has been set.
      * physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
      * @return True if the 'object' field has been set, false otherwise.
      */
    public boolean hasObject() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'object' field.
      * physical name of the object from which it is readed. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.Source.Builder clearObject() {
      object = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Source build() {
      try {
        Source record = new Source();
        record.probeName = fieldSetFlags()[0] ? this.probeName : (java.lang.String) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.schema = fieldSetFlags()[2] ? this.schema : (java.lang.String) defaultValue(fields()[2]);
        record.object = fieldSetFlags()[3] ? this.object : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Source>
    WRITER$ = (org.apache.avro.io.DatumWriter<Source>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Source>
    READER$ = (org.apache.avro.io.DatumReader<Source>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.probeName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.probeName);
    }

    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    if (this.schema == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.schema);
    }

    if (this.object == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.object);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.probeName = null;
      } else {
        this.probeName = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.schema = null;
      } else {
        this.schema = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.object = null;
      } else {
        this.object = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.probeName = null;
          } else {
            this.probeName = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.schema = null;
          } else {
            this.schema = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.object = null;
          } else {
            this.object = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










