/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Definition for windowed timeFrames */
@org.apache.avro.specific.AvroGenerated
public class WindowTime extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3581620009881649686L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WindowTime\",\"namespace\":\"com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2\",\"doc\":\"Definition for windowed timeFrames\",\"fields\":[{\"name\":\"from\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'\",\"default\":null},{\"name\":\"to\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WindowTime> ENCODER =
      new BinaryMessageEncoder<WindowTime>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WindowTime> DECODER =
      new BinaryMessageDecoder<WindowTime>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WindowTime> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WindowTime> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WindowTime> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WindowTime>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WindowTime to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WindowTime from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WindowTime instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WindowTime fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z' */
   private java.lang.String from;
  /** End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z' */
   private java.lang.String to;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WindowTime() {}

  /**
   * All-args constructor.
   * @param from Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'
   * @param to End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'
   */
  public WindowTime(java.lang.String from, java.lang.String to) {
    this.from = from;
    this.to = to;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return from;
    case 1: return to;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: from = value$ != null ? value$.toString() : null; break;
    case 1: to = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'from' field.
   * @return Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'
   */
  public java.lang.String getFrom() {
    return from;
  }


  /**
   * Sets the value of the 'from' field.
   * Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'
   * @param value the value to set.
   */
  public void setFrom(java.lang.String value) {
    this.from = value;
  }

  /**
   * Gets the value of the 'to' field.
   * @return End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'
   */
  public java.lang.String getTo() {
    return to;
  }


  /**
   * Sets the value of the 'to' field.
   * End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'
   * @param value the value to set.
   */
  public void setTo(java.lang.String value) {
    this.to = value;
  }

  /**
   * Creates a new WindowTime RecordBuilder.
   * @return A new WindowTime RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder newBuilder() {
    return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder();
  }

  /**
   * Creates a new WindowTime RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WindowTime RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder newBuilder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder other) {
    if (other == null) {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder();
    } else {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder(other);
    }
  }

  /**
   * Creates a new WindowTime RecordBuilder by copying an existing WindowTime instance.
   * @param other The existing instance to copy.
   * @return A new WindowTime RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder newBuilder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime other) {
    if (other == null) {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder();
    } else {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder(other);
    }
  }

  /**
   * RecordBuilder for WindowTime instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WindowTime>
    implements org.apache.avro.data.RecordBuilder<WindowTime> {

    /** Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z' */
    private java.lang.String from;
    /** End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z' */
    private java.lang.String to;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.from)) {
        this.from = data().deepCopy(fields()[0].schema(), other.from);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.to)) {
        this.to = data().deepCopy(fields()[1].schema(), other.to);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing WindowTime instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.from)) {
        this.from = data().deepCopy(fields()[0].schema(), other.from);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.to)) {
        this.to = data().deepCopy(fields()[1].schema(), other.to);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'from' field.
      * Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'
      * @return The value.
      */
    public java.lang.String getFrom() {
      return from;
    }


    /**
      * Sets the value of the 'from' field.
      * Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'
      * @param value The value of 'from'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder setFrom(java.lang.String value) {
      validate(fields()[0], value);
      this.from = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'from' field has been set.
      * Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'
      * @return True if the 'from' field has been set, false otherwise.
      */
    public boolean hasFrom() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'from' field.
      * Start of the time window in which the measurement. I.e. '2021-03-24 10:50:00.000Z'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder clearFrom() {
      from = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'to' field.
      * End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'
      * @return The value.
      */
    public java.lang.String getTo() {
      return to;
    }


    /**
      * Sets the value of the 'to' field.
      * End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'
      * @param value The value of 'to'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder setTo(java.lang.String value) {
      validate(fields()[1], value);
      this.to = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'to' field has been set.
      * End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'
      * @return True if the 'to' field has been set, false otherwise.
      */
    public boolean hasTo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'to' field.
      * End of the time window in which the measurement. I.e. '2021-03-24 10:55:00.000Z'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.measurement.v2.WindowTime.Builder clearTo() {
      to = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WindowTime build() {
      try {
        WindowTime record = new WindowTime();
        record.from = fieldSetFlags()[0] ? this.from : (java.lang.String) defaultValue(fields()[0]);
        record.to = fieldSetFlags()[1] ? this.to : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WindowTime>
    WRITER$ = (org.apache.avro.io.DatumWriter<WindowTime>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WindowTime>
    READER$ = (org.apache.avro.io.DatumReader<WindowTime>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.from == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.from);
    }

    if (this.to == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.to);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.from = null;
      } else {
        this.from = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.to = null;
      } else {
        this.to = in.readString();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.from = null;
          } else {
            this.from = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.to = null;
          } else {
            this.to = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










