/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ReducedEventValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6200225610555225503L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReducedEventValue\",\"namespace\":\"com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2\",\"fields\":[{\"name\":\"sourceName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'\",\"default\":null},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated'\",\"default\":null},{\"name\":\"eventTimestamp\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Event Timestamp. I.e. '2021-03-24 10:50:00.000Z'\",\"default\":null},{\"name\":\"kafkaTimestamp\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z'\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ReducedEventValue> ENCODER =
      new BinaryMessageEncoder<ReducedEventValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ReducedEventValue> DECODER =
      new BinaryMessageDecoder<ReducedEventValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ReducedEventValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ReducedEventValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ReducedEventValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ReducedEventValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ReducedEventValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ReducedEventValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ReducedEventValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ReducedEventValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1' */
   private java.lang.String sourceName;
  /** Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated' */
   private java.lang.String name;
  /** Event Timestamp. I.e. '2021-03-24 10:50:00.000Z' */
   private java.lang.String eventTimestamp;
  /** Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z' */
   private java.lang.String kafkaTimestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ReducedEventValue() {}

  /**
   * All-args constructor.
   * @param sourceName Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
   * @param name Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated'
   * @param eventTimestamp Event Timestamp. I.e. '2021-03-24 10:50:00.000Z'
   * @param kafkaTimestamp Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z'
   */
  public ReducedEventValue(java.lang.String sourceName, java.lang.String name, java.lang.String eventTimestamp, java.lang.String kafkaTimestamp) {
    this.sourceName = sourceName;
    this.name = name;
    this.eventTimestamp = eventTimestamp;
    this.kafkaTimestamp = kafkaTimestamp;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sourceName;
    case 1: return name;
    case 2: return eventTimestamp;
    case 3: return kafkaTimestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sourceName = value$ != null ? value$.toString() : null; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: eventTimestamp = value$ != null ? value$.toString() : null; break;
    case 3: kafkaTimestamp = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sourceName' field.
   * @return Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
   */
  public java.lang.String getSourceName() {
    return sourceName;
  }


  /**
   * Sets the value of the 'sourceName' field.
   * Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
   * @param value the value to set.
   */
  public void setSourceName(java.lang.String value) {
    this.sourceName = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated'
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated'
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'eventTimestamp' field.
   * @return Event Timestamp. I.e. '2021-03-24 10:50:00.000Z'
   */
  public java.lang.String getEventTimestamp() {
    return eventTimestamp;
  }


  /**
   * Sets the value of the 'eventTimestamp' field.
   * Event Timestamp. I.e. '2021-03-24 10:50:00.000Z'
   * @param value the value to set.
   */
  public void setEventTimestamp(java.lang.String value) {
    this.eventTimestamp = value;
  }

  /**
   * Gets the value of the 'kafkaTimestamp' field.
   * @return Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z'
   */
  public java.lang.String getKafkaTimestamp() {
    return kafkaTimestamp;
  }


  /**
   * Sets the value of the 'kafkaTimestamp' field.
   * Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z'
   * @param value the value to set.
   */
  public void setKafkaTimestamp(java.lang.String value) {
    this.kafkaTimestamp = value;
  }

  /**
   * Creates a new ReducedEventValue RecordBuilder.
   * @return A new ReducedEventValue RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder newBuilder() {
    return new com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder();
  }

  /**
   * Creates a new ReducedEventValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ReducedEventValue RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder newBuilder(com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder other) {
    if (other == null) {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder();
    } else {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder(other);
    }
  }

  /**
   * Creates a new ReducedEventValue RecordBuilder by copying an existing ReducedEventValue instance.
   * @param other The existing instance to copy.
   * @return A new ReducedEventValue RecordBuilder
   */
  public static com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder newBuilder(com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue other) {
    if (other == null) {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder();
    } else {
      return new com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for ReducedEventValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReducedEventValue>
    implements org.apache.avro.data.RecordBuilder<ReducedEventValue> {

    /** Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1' */
    private java.lang.String sourceName;
    /** Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated' */
    private java.lang.String name;
    /** Event Timestamp. I.e. '2021-03-24 10:50:00.000Z' */
    private java.lang.String eventTimestamp;
    /** Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z' */
    private java.lang.String kafkaTimestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sourceName)) {
        this.sourceName = data().deepCopy(fields()[0].schema(), other.sourceName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[2].schema(), other.eventTimestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.kafkaTimestamp)) {
        this.kafkaTimestamp = data().deepCopy(fields()[3].schema(), other.kafkaTimestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ReducedEventValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sourceName)) {
        this.sourceName = data().deepCopy(fields()[0].schema(), other.sourceName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[2].schema(), other.eventTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.kafkaTimestamp)) {
        this.kafkaTimestamp = data().deepCopy(fields()[3].schema(), other.kafkaTimestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'sourceName' field.
      * Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
      * @return The value.
      */
    public java.lang.String getSourceName() {
      return sourceName;
    }


    /**
      * Sets the value of the 'sourceName' field.
      * Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
      * @param value The value of 'sourceName'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder setSourceName(java.lang.String value) {
      validate(fields()[0], value);
      this.sourceName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sourceName' field has been set.
      * Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
      * @return True if the 'sourceName' field has been set, false otherwise.
      */
    public boolean hasSourceName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sourceName' field.
      * Source name (topic) of the measurement. I.e. 'comercial.za.des.productoterminado.mocacota.public.v1'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder clearSourceName() {
      sourceName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated'
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated'
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated'
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * Name of the entity of the event added to the measurement. I.e. 'MocacotaCreated'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTimestamp' field.
      * Event Timestamp. I.e. '2021-03-24 10:50:00.000Z'
      * @return The value.
      */
    public java.lang.String getEventTimestamp() {
      return eventTimestamp;
    }


    /**
      * Sets the value of the 'eventTimestamp' field.
      * Event Timestamp. I.e. '2021-03-24 10:50:00.000Z'
      * @param value The value of 'eventTimestamp'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder setEventTimestamp(java.lang.String value) {
      validate(fields()[2], value);
      this.eventTimestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTimestamp' field has been set.
      * Event Timestamp. I.e. '2021-03-24 10:50:00.000Z'
      * @return True if the 'eventTimestamp' field has been set, false otherwise.
      */
    public boolean hasEventTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'eventTimestamp' field.
      * Event Timestamp. I.e. '2021-03-24 10:50:00.000Z'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder clearEventTimestamp() {
      eventTimestamp = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'kafkaTimestamp' field.
      * Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z'
      * @return The value.
      */
    public java.lang.String getKafkaTimestamp() {
      return kafkaTimestamp;
    }


    /**
      * Sets the value of the 'kafkaTimestamp' field.
      * Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z'
      * @param value The value of 'kafkaTimestamp'.
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder setKafkaTimestamp(java.lang.String value) {
      validate(fields()[3], value);
      this.kafkaTimestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'kafkaTimestamp' field has been set.
      * Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z'
      * @return True if the 'kafkaTimestamp' field has been set, false otherwise.
      */
    public boolean hasKafkaTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'kafkaTimestamp' field.
      * Timestamp when the event arrived to Kafka. I.e. '2021-03-24 10:50:01.000Z'
      * @return This builder.
      */
    public com.inditex.ofda.epmlqsrc.model.autogenerated.reduced.event.v2.ReducedEventValue.Builder clearKafkaTimestamp() {
      kafkaTimestamp = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ReducedEventValue build() {
      try {
        ReducedEventValue record = new ReducedEventValue();
        record.sourceName = fieldSetFlags()[0] ? this.sourceName : (java.lang.String) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.eventTimestamp = fieldSetFlags()[2] ? this.eventTimestamp : (java.lang.String) defaultValue(fields()[2]);
        record.kafkaTimestamp = fieldSetFlags()[3] ? this.kafkaTimestamp : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ReducedEventValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<ReducedEventValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ReducedEventValue>
    READER$ = (org.apache.avro.io.DatumReader<ReducedEventValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.sourceName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.sourceName);
    }

    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    if (this.eventTimestamp == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.eventTimestamp);
    }

    if (this.kafkaTimestamp == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.kafkaTimestamp);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.sourceName = null;
      } else {
        this.sourceName = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.eventTimestamp = null;
      } else {
        this.eventTimestamp = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.kafkaTimestamp = null;
      } else {
        this.kafkaTimestamp = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sourceName = null;
          } else {
            this.sourceName = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.eventTimestamp = null;
          } else {
            this.eventTimestamp = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.kafkaTimestamp = null;
          } else {
            this.kafkaTimestamp = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










